//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace rapidInfoModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class rapidInfoEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new rapidInfoEntities object using the connection string found in the 'rapidInfoEntities' section of the application configuration file.
        /// </summary>
        public rapidInfoEntities() : base("name=rapidInfoEntities", "rapidInfoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new rapidInfoEntities object.
        /// </summary>
        public rapidInfoEntities(string connectionString) : base(connectionString, "rapidInfoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new rapidInfoEntities object.
        /// </summary>
        public rapidInfoEntities(EntityConnection connection) : base(connection, "rapidInfoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Area> Areas
        {
            get
            {
                if ((_Areas == null))
                {
                    _Areas = base.CreateObjectSet<Area>("Areas");
                }
                return _Areas;
            }
        }
        private ObjectSet<Area> _Areas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AreaLink> AreaLinks
        {
            get
            {
                if ((_AreaLinks == null))
                {
                    _AreaLinks = base.CreateObjectSet<AreaLink>("AreaLinks");
                }
                return _AreaLinks;
            }
        }
        private ObjectSet<AreaLink> _AreaLinks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Identity> Identities
        {
            get
            {
                if ((_Identities == null))
                {
                    _Identities = base.CreateObjectSet<Identity>("Identities");
                }
                return _Identities;
            }
        }
        private ObjectSet<Identity> _Identities;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Areas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAreas(Area area)
        {
            base.AddObject("Areas", area);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AreaLinks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAreaLinks(AreaLink areaLink)
        {
            base.AddObject("AreaLinks", areaLink);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Identities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIdentities(Identity identity)
        {
            base.AddObject("Identities", identity);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rapidInfoModel", Name="Area")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Area : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Area object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Area CreateArea(global::System.Int32 id)
        {
            Area area = new Area();
            area.Id = id;
            return area;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value, "ParentId");
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Int32> value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LUDate
        {
            get
            {
                return _LUDate;
            }
            set
            {
                OnLUDateChanging(value);
                ReportPropertyChanging("LUDate");
                _LUDate = StructuralObject.SetValidValue(value, "LUDate");
                ReportPropertyChanged("LUDate");
                OnLUDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LUDate;
        partial void OnLUDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLUDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LUBy
        {
            get
            {
                return _LUBy;
            }
            set
            {
                OnLUByChanging(value);
                ReportPropertyChanging("LUBy");
                _LUBy = StructuralObject.SetValidValue(value, true, "LUBy");
                ReportPropertyChanged("LUBy");
                OnLUByChanged();
            }
        }
        private global::System.String _LUBy;
        partial void OnLUByChanging(global::System.String value);
        partial void OnLUByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CRC
        {
            get
            {
                return _CRC;
            }
            set
            {
                OnCRCChanging(value);
                ReportPropertyChanging("CRC");
                _CRC = StructuralObject.SetValidValue(value, true, "CRC");
                ReportPropertyChanged("CRC");
                OnCRCChanged();
            }
        }
        private global::System.String _CRC;
        partial void OnCRCChanging(global::System.String value);
        partial void OnCRCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MachineID
        {
            get
            {
                return _MachineID;
            }
            set
            {
                OnMachineIDChanging(value);
                ReportPropertyChanging("MachineID");
                _MachineID = StructuralObject.SetValidValue(value, true, "MachineID");
                ReportPropertyChanged("MachineID");
                OnMachineIDChanged();
            }
        }
        private global::System.String _MachineID;
        partial void OnMachineIDChanging(global::System.String value);
        partial void OnMachineIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DirtyFlag
        {
            get
            {
                return _DirtyFlag;
            }
            set
            {
                OnDirtyFlagChanging(value);
                ReportPropertyChanging("DirtyFlag");
                _DirtyFlag = StructuralObject.SetValidValue(value, "DirtyFlag");
                ReportPropertyChanged("DirtyFlag");
                OnDirtyFlagChanged();
            }
        }
        private Nullable<global::System.Int32> _DirtyFlag;
        partial void OnDirtyFlagChanging(Nullable<global::System.Int32> value);
        partial void OnDirtyFlagChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rapidInfoModel", Name="AreaLink")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AreaLink : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AreaLink object.
        /// </summary>
        /// <param name="identityId">Initial value of the IdentityId property.</param>
        /// <param name="areaId">Initial value of the AreaId property.</param>
        public static AreaLink CreateAreaLink(global::System.Int32 identityId, global::System.Int32 areaId)
        {
            AreaLink areaLink = new AreaLink();
            areaLink.IdentityId = identityId;
            areaLink.AreaId = areaId;
            return areaLink;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdentityId
        {
            get
            {
                return _IdentityId;
            }
            set
            {
                if (_IdentityId != value)
                {
                    OnIdentityIdChanging(value);
                    ReportPropertyChanging("IdentityId");
                    _IdentityId = StructuralObject.SetValidValue(value, "IdentityId");
                    ReportPropertyChanged("IdentityId");
                    OnIdentityIdChanged();
                }
            }
        }
        private global::System.Int32 _IdentityId;
        partial void OnIdentityIdChanging(global::System.Int32 value);
        partial void OnIdentityIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AreaId
        {
            get
            {
                return _AreaId;
            }
            set
            {
                if (_AreaId != value)
                {
                    OnAreaIdChanging(value);
                    ReportPropertyChanging("AreaId");
                    _AreaId = StructuralObject.SetValidValue(value, "AreaId");
                    ReportPropertyChanged("AreaId");
                    OnAreaIdChanged();
                }
            }
        }
        private global::System.Int32 _AreaId;
        partial void OnAreaIdChanging(global::System.Int32 value);
        partial void OnAreaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LUDate
        {
            get
            {
                return _LUDate;
            }
            set
            {
                OnLUDateChanging(value);
                ReportPropertyChanging("LUDate");
                _LUDate = StructuralObject.SetValidValue(value, "LUDate");
                ReportPropertyChanged("LUDate");
                OnLUDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LUDate;
        partial void OnLUDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLUDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LUBy
        {
            get
            {
                return _LUBy;
            }
            set
            {
                OnLUByChanging(value);
                ReportPropertyChanging("LUBy");
                _LUBy = StructuralObject.SetValidValue(value, true, "LUBy");
                ReportPropertyChanged("LUBy");
                OnLUByChanged();
            }
        }
        private global::System.String _LUBy;
        partial void OnLUByChanging(global::System.String value);
        partial void OnLUByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CRC
        {
            get
            {
                return _CRC;
            }
            set
            {
                OnCRCChanging(value);
                ReportPropertyChanging("CRC");
                _CRC = StructuralObject.SetValidValue(value, true, "CRC");
                ReportPropertyChanged("CRC");
                OnCRCChanged();
            }
        }
        private global::System.String _CRC;
        partial void OnCRCChanging(global::System.String value);
        partial void OnCRCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MachineID
        {
            get
            {
                return _MachineID;
            }
            set
            {
                OnMachineIDChanging(value);
                ReportPropertyChanging("MachineID");
                _MachineID = StructuralObject.SetValidValue(value, true, "MachineID");
                ReportPropertyChanged("MachineID");
                OnMachineIDChanged();
            }
        }
        private global::System.String _MachineID;
        partial void OnMachineIDChanging(global::System.String value);
        partial void OnMachineIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DirtyFlag
        {
            get
            {
                return _DirtyFlag;
            }
            set
            {
                OnDirtyFlagChanging(value);
                ReportPropertyChanging("DirtyFlag");
                _DirtyFlag = StructuralObject.SetValidValue(value, "DirtyFlag");
                ReportPropertyChanged("DirtyFlag");
                OnDirtyFlagChanged();
            }
        }
        private Nullable<global::System.Int32> _DirtyFlag;
        partial void OnDirtyFlagChanging(Nullable<global::System.Int32> value);
        partial void OnDirtyFlagChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rapidInfoModel", Name="Identity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Identity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Identity object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Identity CreateIdentity(global::System.Int32 id)
        {
            Identity identity = new Identity();
            identity.Id = id;
            return identity;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DetailsLength
        {
            get
            {
                return _DetailsLength;
            }
            set
            {
                OnDetailsLengthChanging(value);
                ReportPropertyChanging("DetailsLength");
                _DetailsLength = StructuralObject.SetValidValue(value, "DetailsLength");
                ReportPropertyChanged("DetailsLength");
                OnDetailsLengthChanged();
            }
        }
        private Nullable<global::System.Int32> _DetailsLength;
        partial void OnDetailsLengthChanging(Nullable<global::System.Int32> value);
        partial void OnDetailsLengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Details
        {
            get
            {
                return StructuralObject.GetValidValue(_Details);
            }
            set
            {
                OnDetailsChanging(value);
                ReportPropertyChanging("Details");
                _Details = StructuralObject.SetValidValue(value, true, "Details");
                ReportPropertyChanged("Details");
                OnDetailsChanged();
            }
        }
        private global::System.Byte[] _Details;
        partial void OnDetailsChanging(global::System.Byte[] value);
        partial void OnDetailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdate
        {
            get
            {
                return _LastUpdate;
            }
            set
            {
                OnLastUpdateChanging(value);
                ReportPropertyChanging("LastUpdate");
                _LastUpdate = StructuralObject.SetValidValue(value, "LastUpdate");
                ReportPropertyChanged("LastUpdate");
                OnLastUpdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdate;
        partial void OnLastUpdateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LUDate
        {
            get
            {
                return _LUDate;
            }
            set
            {
                OnLUDateChanging(value);
                ReportPropertyChanging("LUDate");
                _LUDate = StructuralObject.SetValidValue(value, "LUDate");
                ReportPropertyChanged("LUDate");
                OnLUDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LUDate;
        partial void OnLUDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLUDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LUBy
        {
            get
            {
                return _LUBy;
            }
            set
            {
                OnLUByChanging(value);
                ReportPropertyChanging("LUBy");
                _LUBy = StructuralObject.SetValidValue(value, true, "LUBy");
                ReportPropertyChanged("LUBy");
                OnLUByChanged();
            }
        }
        private global::System.String _LUBy;
        partial void OnLUByChanging(global::System.String value);
        partial void OnLUByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CRC
        {
            get
            {
                return _CRC;
            }
            set
            {
                OnCRCChanging(value);
                ReportPropertyChanging("CRC");
                _CRC = StructuralObject.SetValidValue(value, true, "CRC");
                ReportPropertyChanged("CRC");
                OnCRCChanged();
            }
        }
        private global::System.String _CRC;
        partial void OnCRCChanging(global::System.String value);
        partial void OnCRCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MachineID
        {
            get
            {
                return _MachineID;
            }
            set
            {
                OnMachineIDChanging(value);
                ReportPropertyChanging("MachineID");
                _MachineID = StructuralObject.SetValidValue(value, true, "MachineID");
                ReportPropertyChanged("MachineID");
                OnMachineIDChanged();
            }
        }
        private global::System.String _MachineID;
        partial void OnMachineIDChanging(global::System.String value);
        partial void OnMachineIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DirtyFlag
        {
            get
            {
                return _DirtyFlag;
            }
            set
            {
                OnDirtyFlagChanging(value);
                ReportPropertyChanging("DirtyFlag");
                _DirtyFlag = StructuralObject.SetValidValue(value, "DirtyFlag");
                ReportPropertyChanged("DirtyFlag");
                OnDirtyFlagChanged();
            }
        }
        private Nullable<global::System.Int32> _DirtyFlag;
        partial void OnDirtyFlagChanging(Nullable<global::System.Int32> value);
        partial void OnDirtyFlagChanged();

        #endregion

    }

    #endregion

}
